kind: PodAutoscaler
metadata:
  name: Llama-3.1-8B-hpa
  namespace: default
spec:
  scalingStrategy: HPA
  minReplicas: 1
  maxReplicas: 8
  metricsSources:
    - metricSourceType: pod
      protocolType: http
      port: '8000'
      path: /metrics
      targetMetric: gpu_cache_usage_perc
      targetValue: '70'
  scaleTargetRef:
    name: Llama-3.1-8B